# Those are publisher names.
# cSpell:ignore  subosito

name: Tests
on:
  push:
    branches:
      - master

jobs:
  packages:
    runs-on: ubuntu-latest
    # Lists of all packages
    outputs:
      package: ${{ steps.changes.outputs.packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          packages=$((
            echo '{ "package" : ['
            ls -a1d packages/*/ | cut -d/ -f 1-2  | sed 's/^\(.*\)$/\\"\1\\",/' | xargs | sed 's/,$//g'
            echo ']}'
          ) | jq -c .)
          echo "::set-output name=packages::$packages"
      - name: echo modified packages
        run: |
          echo ${{ steps.changes.outputs.packages }}
  test:
    runs-on: macos-latest
    name: Dart linter and tests
    needs: packages
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.packages.outputs.package) }}
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Run tests
        run: flutter test --coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
